#======= This is like an Ad, you can automatically broadcast =======
#======= You can change the Broadcast time by changing the "broadcasttime" option =======
options:
	broadcasttime: 20

every {@broadcasttime} minutes:
	if {autobroadcast} is not set:
		stop
	else:
		broadcast "&8[<#F3CF00>Autobroadcast&8] &r%{autobroadcast}%"

command /setautobroadcast <text>:
	permission: autobroadcast.set
	trigger:
		if arg-1 is not set:
			delete {autobroadcast}
			send "<#FF0000>Deleted Autobroadcast Message"
		set {_ab} to arg-1
		set {autobroadcast} to colored {_ab}
		send "&8[<#F3CF00>Autobroadcast&8] <#18FF00>Broadcasting message set succesfully!"
