#======= Please read the "#"-comments before using the "/broadcast bossbar" command! =======
command /broadcast <text> <text>:
	permission: broadcast.use
	trigger:
		if arg-1 is not set:
			send "<#FF0000>Type and Message missing! Use 'text', 'actionbar', 'title', or 'bossbar' as the type!"
			stop
		if arg-2 is not set:
			send "<#FF0000>Message missing!"
			stop

		set {_type} to arg-1
		set {_message} to arg-2

#======= Broadcasting as Text =======
		if arg-1 is "text":
			broadcast ""
			broadcast "<#0045FF>Broadcast <#A7A7A7>- <#E3D66C>%{_message}%"
			broadcast ""
			loop all players:
				play sound "entity.experience_orb.pickup" with volume 0.5 and pitch 1.5 at location of loop-player for loop-player
			set {_chatpause} to true
			wait 10 seconds
			set {_chatpause} to false
			stop

#======= Broadcasting as Actionbar =======
		if arg-1 is "actionbar":
			loop all players:
				loop 5 times:
					send actionbar "<#0045FF>Broadcast <#A7A7A7>- <#E3D66C>%{_message}%" to loop-player
					play sound "entity.experience_orb.pickup" with volume 0.5 and pitch 1.5 at location of loop-player for loop-player
					wait 2 seconds
			stop

#======= Broadcasting as Title =======
		if arg-1 is "title":
			set {_countdown} to 10
			loop all players:
				loop 10 times:
					send title "<#0045FF>Broadcast <#A7A7A7>- <#4074FF>%{_countdown}%s" with subtitle "<#E3D66C>%{_message}%" to loop-player
					play sound "entity.experience_orb.pickup" with volume 0.5 and pitch 1.5 at location of loop-player for loop-player
					remove 1 from {_countdown}
					wait 1 second
			set {_countdown} to 0
			stop

#======= Broadcasting as Bossbar =======
#======= Be careful! Executing this command will lead to 6 Bossbar deletions, which leads to messages from the server, that appear in the In-game chat!=======
		if arg-1 is "bossbar":
			loop 6 times:
				if loop-value = 6:
					set {_bar} to a boss bar:
						set color of event-bossbar to blue
						set title of event-bossbar to "<#0045FF>Broadcast <#A7A7A7>- <#E3D66C>%{_message}%"
						set progress of event-bossbar to 0%
						set style of event-bossbar to 10 segments
					loop all players:
						add loop-player to viewers of {_bar}
						play sound "entity.experience_orb.pickup" with volume 0.5 and pitch 1.5 at location of loop-player for loop-player
				if loop-value = 5:
					set {_bar} to a boss bar:
						set color of event-bossbar to blue
						set title of event-bossbar to "<#0045FF>Broadcast <#A7A7A7>- <#E3D66C>%{_message}%"
						set progress of event-bossbar to 20%
						set style of event-bossbar to 10 segments
					loop all players:
						add loop-player to viewers of {_bar}
						play sound "entity.experience_orb.pickup" with volume 0.5 and pitch 1.5 at location of loop-player for loop-player
				if loop-value = 4:
					set {_bar} to a boss bar:
						set color of event-bossbar to blue
						set title of event-bossbar to "<#0045FF>Broadcast <#A7A7A7>- <#E3D66C>%{_message}%"
						set progress of event-bossbar to 40%
						set style of event-bossbar to 10 segments
					loop all players:
						add loop-player to viewers of {_bar}
						play sound "entity.experience_orb.pickup" with volume 0.5 and pitch 1.5 at location of loop-player for loop-player
				if loop-value = 3:
					set {_bar} to a boss bar:
						set color of event-bossbar to blue
						set title of event-bossbar to "<#0045FF>Broadcast <#A7A7A7>- <#E3D66C>%{_message}%"
						set progress of event-bossbar to 60%
						set style of event-bossbar to 10 segments
					loop all players:
						add loop-player to viewers of {_bar}
						play sound "entity.experience_orb.pickup" with volume 0.5 and pitch 1.5 at location of loop-player for loop-player
				if loop-value = 2:
					set {_bar} to a boss bar:
						set color of event-bossbar to blue
						set title of event-bossbar to "<#0045FF>Broadcast <#A7A7A7>- <#E3D66C>%{_message}%"
						set progress of event-bossbar to 80%
						set style of event-bossbar to 10 segments
					loop all players:
						add loop-player to viewers of {_bar}
						play sound "entity.experience_orb.pickup" with volume 0.5 and pitch 1.5 at location of loop-player for loop-player
				if loop-value = 1:
					set {_bar} to a boss bar:
						set color of event-bossbar to blue
						set title of event-bossbar to "<#0045FF>Broadcast <#A7A7A7>- <#E3D66C>%{_message}%"
						set progress of event-bossbar to 100%
						set style of event-bossbar to 10 segments
					loop all players:
						add loop-player to viewers of {_bar}
						play sound "entity.experience_orb.pickup" with volume 0.5 and pitch 1.5 at location of loop-player for loop-player
				wait 2 seconds
				remove all players from viewers of {_bar}
				delete {_bar}
           
on tab complete for "/broadcast":
	set tab completion for position 1 to "text" and "actionbar" and "title" and "bossbar"
