#======= This script will work even though it will throw 2 problems =======
options:
	combattime: "30"

#======= General Combat system =======
on damage:
	if attacker is a player:
		if victim is a player:
			add victim to {combat::*}
			add attacker to {combat::*}
			set {combat.%victim%} to {@combattime}
			set {combat.%attacker%} to {@combattime}
			send "&8[<#F3CF00>Combatsystem&8] <#FF0000>You are in combat for %{@combattime}% seconds!" to victim
			send "&8[<#F3CF00>Combatsystem&8] <#FF0000>You are in combat for %{@combattime}% seconds!" to attacker

#======= Combat duration decrease =======
every 1 second:
	loop {combat::*}:
		set {_p} to loop-index parsed as player
		remove 1 from {combat.%{_p}%}
		if {combat.%{_p}%} > 0:
			send actionbar "&8[<#F3CF00>Combatsystem&8] <#FF0000>Combat: %{combat.%{_p}%}% seconds" to {_p}
		if {combat.%{_p}%} = 0:
			send "&8[<#F3CF00>Combatsystem&8] <#18FF00>Combat ended!" to {_p}
			remove {_p} from {combat::*}

#======= Killing users that quit during combat =======
on quit:
	if {combat.%player%} = 0:
		stop
	if {combat.%player%} is not set:
		stop
	if {combat.%player%} > 0:
		kill player
		set {combatkilled.%player%} to true

on join:
	if {combatkilled.%player%} is true:
		send "&8[<#F3CF00>Combatsystem&8] <#FF0000>You habe been killed, because you logged out during combat!"
		set {combatkilled.%player%} to false

#======= Resetting on death =======
on death:
	if {combat.%victim%} > 0:
		set {combat.%victim%} to 0
