#======= Script that lets you create and manage Crates =======
command /crateeditor:
	permission: edit.crates
	trigger:
		give player recovery compass named "<#FFE700>Crate Editor" with lore "<#18FF00>Rightclick a Crate using this Item to open the Settings menu."
		send "<#18FF00>Received Crate Editor Item"

command /cratekey <text> [<integer>] [<player>]:
	permission: givekey.crate
	trigger:
		if {crate::keys::%arg-1%::clean} is set:
			set {_key} to tripwire hook named {crate::keys::%arg-1%::name} with lore "<#6E6E6E>- Rightclick a Crate using this item"
		set {_target} to player
		if arg-3 is set:
			set {_target} to arg-3
		if arg-2 is set:
			set {_int} to arg-2
		else:
			set {_int} to 1
		give {_target} {_int} of {_key}
		send "<#18FF00>Gave 1x <#FFE700>%name of {_key}% <#18FF00>to <#FFE700>%name of {_target}%<#18FF00>!" to player

on tab complete of "/cratekey":
	if player has permission "givekey.crate":
		loop {crate_key_list::*}:
			add loop-value to {_completions::*}
		add {_completions::*} to tab completions for position 1

on right click:
	if "%event-block%" contains "shulker box":
		if player's tool is recovery compass:
			if player has permission "edit.crates":
				if name of player's tool is "<#FFE700>Crate Editor":
					if lore of player's tool is "<#18FF00>Rightclick a Crate using this Item to open the Settings menu.":
						cancel event
						set metadata tag "CurrentCrate" of player to location of event-block
						set {_settings} to new chest inventory with 3 rows named "<#FFE700>Crate Settings"
						set {_slot} to 0
						loop 10 times:
							set slot {_slot} of {_settings} to gray stained glass pane named ""
							add 1 to {_slot}
						set slot 10 of {_settings} to tripwire hook named "<#FFE700>Set Key for Crate"
						set slot 11 of {_settings} to name tag named "<#FFE700>Set Name of Crate"
						set slot 13 of {_settings} to chest named "<#FFE700>Set Lootpool of Crate"
						set slot 15 of {_settings} to barrier named "<#FF0000>Delete Crate"
						set {_loc} to location of event-block
						if {crate::%{_loc}%::exists} is not set:
							set slot 16 of {_settings} to lime dye named "<#18FF00>Create Crate"
							set slot 4 of {_settings} to shulker box named "<#7F7F7F>Crate not existing"
						else:
							set slot 4 of {_settings} to shulker box named "%{crate::%{_loc}%::name}%"
						set {_slot} to 17
						loop 10 times:
							set slot {_slot} of {_settings} to gray stained glass pane named ""
							add 1 to {_slot}
						open {_settings} to player
		else if player's tool is tripwire hook:
			cancel event
			set {_name} to name of player's tool
			if lore of player's tool is "<#6E6E6E>- Rightclick a Crate using this item":
				set {_loc} to location of event-block
				if {crate::%{_loc}%::key::name} is {_name}:
					set metadata tag "IsOpeningCrate" of player to true
					set metadata tag "ActiveCrateInventory" of player to {crate::%{_loc}%::name}
					set {_c} to new chest inventory named {crate::%{_loc}%::name}
					remove 1 of player's tool from player's tool
					play sound "block.chest.open" with volume 1 and pitch 1 at {_loc} for player
					set {_slot} to 0
					loop 9 times:
						set slot {_slot} of {_c} to gray stained glass pane named ""
						set {_slot} to {_slot} + 1
					set {_slot} to 18
					loop 9 times:
						set slot {_slot} of {_c} to gray stained glass pane named ""
						set {_slot} to {_slot} + 1
					set slot 4 of {_c} to lime stained glass pane named ""
					set slot 22 of {_c} to lime stained glass pane named ""
					set {_slot} to 9
					loop 9 times:
						set slot {_slot} of {_c} to random element out of {crate::%{_loc}%::lootpool::*}
						set {_slot} to {_slot} + 1
					open {_c} to player
					set {_particleloc} to {_loc}
					add 1.2 to y-coordinate of {_particleloc}
					set {_wait} to 0.1 seconds
					loop 30 times:
						set {_slot} to 9
						loop 8 times:
							set slot {_slot} of {_c} to slot {_slot} + 1 of {_c}
							set {_slot} to {_slot} + 1
						set slot 17 of {_c} to random element out of {crate::%{_loc}%::lootpool::*}
						play sound "entity.experience_orb.pickup" with volume 0.5 and pitch 1.5 at {_loc} for player
						make 3 of flame particle at {_particleloc} with extra 0.1
						wait {_wait}
					set {_wait} to 0.3 seconds
					loop 15 times:
						set {_slot} to 9
						loop 8 times:
							set slot {_slot} of {_c} to slot {_slot} + 1 of {_c}
							set {_slot} to {_slot} + 1
						set slot 17 of {_c} to random element out of {crate::%{_loc}%::lootpool::*}
						play sound "entity.experience_orb.pickup" with volume 0.5 and pitch 1.2 at {_loc} for player
						make 3 of flame particle at {_particleloc} with extra 0.1
						wait {_wait}
					set {_wait} to 0.5 seconds
					loop 5 times:
						set {_slot} to 9
						loop 8 times:
							set slot {_slot} of {_c} to slot {_slot} + 1 of {_c}
							set {_slot} to {_slot} + 1
						set slot 17 of {_c} to random element out of {crate::%{_loc}%::lootpool::*}
						play sound "entity.experience_orb.pickup" with volume 0.5 and pitch 1.0 at {_loc} for player
						make 3 of flame particle at {_particleloc} with extra 0.1
						wait {_wait}
					set {_wait} to 0.8 seconds
					set {_slot} to 9
					loop 8 times:
						set slot {_slot} of {_c} to slot {_slot} + 1 of {_c}
						set {_slot} to {_slot} + 1
					set slot 17 of {_c} to random element out of {crate::%{_loc}%::lootpool::*}
					play sound "entity.experience_orb.pickup" with volume 0.6 and pitch 0.8 at {_loc} for player
					make 3 of flame particle at {_particleloc} with extra 0.1
					wait {_wait}
					make 20 of explosion particle at {_particleloc} with extra 0.2
					play sound "entity.player.levelup" with volume 1 and pitch 1 at {_loc} for player
					if metadata tag "IsOpeningCrate" of player is true:
						set {_reward} to slot 13 of {_c}
						give player {_reward}
						send "<#18FF00>You received %{_reward}%!" to player
						delete metadata tag "IsOpeningCrate" of player
						delete metadata tag "ActiveCrateInventory" of player
						close player's inventory
		else:
			set {_loc} to location of event-block
			if {crate::%{_loc}%::exists} is true:
				cancel event
				send "<#FF0000>You need the Crate Key %{crate::%{_loc}%::key::name}% <#FF0000>(ID: %{crate::%{_loc}%::key::clean}%)!"



on inventory close:
	if metadata tag "IsOpeningCrate" of player is true:
		if name of event-inventory is metadata tag "ActiveCrateInventory" of player:
			set {_reward} to slot 13 of event-inventory
			give player {_reward}
			play sound "entity.player.levelup" with volume 1 and pitch 1.2 at player for player
			send "<#18FF00>You received %{_reward}%!" to player
			delete metadata tag "IsOpeningCrate" of player
			delete metadata tag "ActiveCrateInventory" of player

on inventory click:
	if metadata tag "IsOpeningCrate" of player is true:
		if name of event-inventory is metadata tag "ActiveCrateInventory" of player:
			cancel event

on block break:
	if "%event-block%" contains "shulker box":
		set {_loc} to location of event-block
		if {crate::%{_loc}%::exists} is true:
			cancel event
			if player has permission "edit.crates":
				send "<#FF0000>If you want to remove this Crate, please delete it in the Crate Settings Menu!"



on inventory click:
	if name of event-inventory is "<#FFE700>Crate Settings":
		cancel event
		set {_loc} to metadata tag "CurrentCrate" of player
		if {_loc} is not set:
			stop
		if index of event-slot is 10:
			if {crate::%{_loc}%::exists} is not set:
				send "<#FF0000>You must create the crate first!" to player
				stop
			close player's inventory
			set metadata tag "AnvilType" of player to "SetKeyName"
			open real anvil inventory named "Set Key Name" to player
			wait 1 tick
			set slot 0 of player's current inventory to name tag named "Enter Key Name"
		else if index of event-slot is 11:
			if {crate::%{_loc}%::exists} is not set:
				send "<#FF0000>You must create the crate first!" to player
				stop
			close player's inventory
			set metadata tag "AnvilType" of player to "RenameCrate"
			open real anvil inventory named "Rename Crate" to player
			wait 1 tick
			set slot 0 of player's current inventory to name tag named "Enter Crate Name"
		else if index of event-slot is 13:
			if {crate::%{_loc}%::exists} is not set:
				send "<#FF0000>You must create the crate first!" to player
				stop
			close player's inventory
			set {_lootpool_gui} to new chest inventory with 6 rows named "Crate Lootpool"
			set {_slot} to 0
			loop 54 times:
				if {crate::%{_loc}%::lootpool::%{_slot}%} is set:
					set slot {_slot} of {_lootpool_gui} to {crate::%{_loc}%::lootpool::%{_slot}%}
				add 1 to {_slot}
			open {_lootpool_gui} to player
		else if index of event-slot is 16:
			if event-slot is lime dye:
				set {crate::%{_loc}%::exists} to true
				set {crate::%{_loc}%::name} to "Crate"
				send "<#18FF00>Crate has been created!"
				close player's inventory
		else if index of event-slot is 15:
			delete {crate::%{_loc}%::exists}
			delete {crate::%{_loc}%::name}
			delete {crate::%{_loc}%::key::*}
			delete {crate::%{_loc}%::lootpool::*}
			send "<#FF0000>Crate has been deleted."
			set block at {_loc} to air
			close player's inventory

on anvil prepare:
	if name of event-inventory is "Rename Crate" or "Set Key Name":
		set anvil repair cost of event-inventory to 0

on inventory click:
	if type of event-inventory is anvil inventory:
		set {_loc} to metadata tag "CurrentCrate" of player
		if {_loc} is not set:
			stop
		if index of event-slot is 0 or 1:
			cancel event
		else if index of event-slot is 2:
			set {_name} to anvil text input of event-inventory
			cancel event
			if {_name} is set:
				set {_type} to metadata tag "AnvilType" of player
				if {_type} is "RenameCrate":
					if {_name} is not "Enter Crate Name":
						set {crate::%{_loc}%::name} to {_name}
						send "<#18FF00>New Crate name: %{crate::%{_loc}%::name}%" to player
						set slot 0 of event-inventory to air
						close player's inventory
						delete metadata tag "CurrentCrate" of player
						delete metadata tag "AnvilType" of player
				else if {_type} is "SetKeyName":
					if {_name} is not "Enter Key Name":
						set {_clean} to uncolored {_name}
						set {_n} to colored {_name}
						replace all " " in {_clean} with "_"
						set {crate::%{_loc}%::key::name} to {_n}
						set {crate::%{_loc}%::key::clean} to {_clean}
						set {crate::keys::%{_clean}%::name} to {_n}
						set {crate::keys::%{_clean}%::clean} to {_clean}
						set {crate_key_list::%{_clean}%} to {_clean}
						send "<#18FF00>Key has been set: %{_n}% <#18FF00>(ID: %{_clean}%)" to player
						set slot 0 of event-inventory to air
						close player's inventory
						delete metadata tag "CurrentCrate" of player
						delete metadata tag "Anviltype" of player
on inventory close:
	if name of event-inventory is "Crate Lootpool":
		set {_loc} to metadata tag "CurrentCrate" of player
		if {_loc} is not set:
			stop
		delete {crate::%{_loc}%::lootpool::*}
		set {_slot} to 0
		loop 54 times:
			set {_item} to slot {_slot} of event-inventory
			if {_item} is set:
				if {_item} is not air:
					set {crate::%{_loc}%::lootpool::%{_slot}%} to {_item}
			add 1 to {_slot}
		send "<#18FF00>Lootpool has been saved successfully!" to player
		delete metadata tag "CurrentCrate" of player












