#======= This script lets you spawn dummys for pvp training =======
command /spawndummy:
	permission: dummy.spawn
	trigger:
		set {_nbt} to nbt compound from "{NoGravity:1b}"
		spawn 1 armor stand at player's location with nbt {_nbt}
		set max health of last spawned armor stand to 1024
		set health of last spawned armor stand to 1024
		set metadata tag "CustomArmorStand" of last spawned armor stand to true
		send "<#18FF00>Succesfully spawned a dummy!"
        
command /removedummy:
	permission: dummy.remove
	trigger:
		set {_target} to targeted entity
		if {_target} is an armor stand:
			delete metadata tag "CustomArmorStand" of targeted entity
			kill {_target}
			send "<#18FF00>Dummy has been removed!"
		else:
			send "<#FF0000>You are not looking at a Dummy!"
			stop
            
on damage of armor stand:
	if metadata tag "CustomArmorStand" of victim is true:
		set {_loc} to location of victim
		set health of victim to 1024
		set {_damage} to damage / 2
		set {_damage} to rounded down {_damage}
		send actionbar "<#18FF00>Dealt <#FFE700>%{_damage}% ❤ <#18FF00>of damage!" to attacker

on death:
	if metadata tag "CustomArmorStand" of victim is true:
		clear drops
		set {_loc} to location of victim
		set {_nbt} to nbt compound from "{NoGravity:1b}"
		spawn 1 armor stand at {_loc} with nbt {_nbt}
		set max health of last spawned armor stand to 1024
		set health of last spawned armor stand to 1024
		set metadata tag "CustomArmorStand" of last spawned armor stand to true
