#======= Script that lets you automatically/manually delete all dropped Items of a set type =======
command /oresclearedit:
	permission: oresclear.settings
	trigger:
		set {_inv} to new chest inventory with 6 rows named "<#FFE700>Oresclear — Edit Itempool"
		loop 54 times:
			set {_slot} to loop-number - 1
			if {oresclear::item::%{_slot}%} is set:
				set {_item} to {oresclear::item::%{_slot}%} parsed as item type
				set slot {_slot} of {_inv} to {_item}
		open {_inv} to player

on inventory close:
	if name of event-inventory is "<#FFE700>Oresclear — Edit Itempool":
		loop 54 times:
			set {_slot} to loop-number - 1
			if slot {_slot} of event-inventory is not air:
				set {oresclear::item::%{_slot}%} to "%type of slot {_slot} of event-inventory%"
			else:
				delete {oresclear::item::%{_slot}%}
		send "<#18FF00>The Itempool has been saved. The given Items will be cleared." to player

every 5 minutes:
	broadcast "<#3A3A3A>[<#FFE700>Oresclear<#3A3A3A>] <#FF0000>Drops will be cleared in 5 minutes!"
	wait 3 minutes
	broadcast "<#3A3A3A>[<#FFE700>Oresclear<#3A3A3A>] <#FF0000>Drops will be cleared in 2 minutes!"
	wait 1 minute
	wait 30 seconds
	broadcast "<#3A3A3A>[<#FFE700>Oresclear<#3A3A3A>] <#FF0000>Drops will be cleared in 30 seconds!"
	wait 30 seconds
	loop all dropped items:
		set {_type} to "%type of item of loop-entity%"
		if {oresclear::item::*} contains {_type}:
			delete loop-entity
	broadcast "<#3A3A3A>[<#FFE700>Oresclear<#3A3A3A>] <#FF0000>Drops have been cleared!"
		
command /oresclear [<number>]:
	permission: oresclear.use
	trigger:
		if arg-1 is not set:
			loop all dropped items:
				set {_type} to "%type of item of loop-entity%"
				if {oresclear::item::*} contains {_type}:
					delete loop-entity
			broadcast "<#3A3A3A>[<#FFE700>Oresclear<#3A3A3A>] <#FF0000>Drops have been cleared!"
		else:
			set {_time} to arg-1
			if {_time} is less than 0.6:
				send "<#FF0000>The time must at least be 0.6 minutes!" to player
				stop
			if {_time} is 1:
				broadcast "<#3A3A3A>[<#FFE700>Oresclear<#3A3A3A>] <#FF0000>Drops will be cleared in 1 minute!"
			else:
				broadcast "<#3A3A3A>[<#FFE700>Oresclear<#3A3A3A>] <#FF0000>Drops will be cleared in %{_time}% minutes!"
			set {_sec} to {_time} * 60
			set {_sec} to {_sec} - 30
			set {_duration} to "%{_sec}% seconds" parsed as timespan
			wait {_duration}
			broadcast "<#3A3A3A>[<#FFE700>Oresclear<#3A3A3A>] <#FF0000>Drops will be cleared in 30 seconds!"
			wait 30 seconds
			loop all dropped items:
				set {_type} to "%type of item of loop-entity%"
				if {oresclear::item::*} contains {_type}:
					delete loop-entity
			broadcast "<#3A3A3A>[<#FFE700>Oresclear<#3A3A3A>] <#FF0000>Drops have been cleared!"
