#======= Unfinished!!!! =======
#======= Change the Scoreboards lines with whatever you want! =======

function reloadScoreboard(p: player):
	set title of {_p}'s scoreboard to "My Scoreboard"
	set line 1 of {_p}'s scoreboard to ""
	set line 2 of {_p}'s scoreboard to "<#38FF12>⚔️ Kills: <#FFDD00>%{kills.%{_p}%}%"
	set line 3 of {_p}'s scoreboard to "<#E60000>☠️ Deaths: <#FFDD00>%{deaths.%{_p}%}%"
	set line 4 of {_p}'s scoreboard to "<#00C6E6>⏰ Playtime: <#FFDD00>%{playtimedays.%{_p}%}%d %{playtimehours.%{_p}%}%h %{playtimeminutes.%{_p}%}%m"
	set line 5 of {_p}'s scoreboard to "<#FFE700>💸 Money: <#FFDD00>%{money.%{_p}%}%"
	set line 6 of {_p}'s scoreboard to "<#5865F2>📢 Discord: "
	set line 7 of {_p}'s scoreboard to ""
#======= Load Scoreboard on join =======

on join:
	function reloadScoreboard(player)

#======= Playtimecounter =======

every one minute:
	loop all players:
		add 1 to {playtime.%loop-player%}
		if {playtime.%loop-player%} = 60:
			set {playtime.%loop-player%} to 0
			add 1 {playtimehours.%loop-player%}
			if {playtimehours.%loop-player%} = 24:
				set {playtimehours.%loop-player%} to 0
				add 1 to {playtimedays.%loop-player%}
		function reloadScoreboard(%loop-player%)

#======= Kill and Death counter =======

on death:
	if victim is a player:
		add 1 to {deaths.%victim%}
		if attacker is a player:
			add 1 to {kills.%attacker%}

#======= Money System =======

on first join:
	set {money.%player%} to 1000 #Change the Money to whatever a player should receive on his first join

command /pay <player> <integer>:
	trigger:
		if arg-2 > {money.%player%}:
			send "<#FF0000>You don't have this amount of money!"
		else:
			add arg-2 to {money.%arg-1%}
			subtract arg-2 from {money.%player%}
			send "<#18FF00>You have succesfully paid <#FFE300>%arg-1% %arg-2% Money<#18FF00>!"
			send "<#18FF00>You received <#FFE300>%arg-2% Money <#18FF00>from <#FFE300>%player%!" to arg-1




