#======= This script lets you set a protected zone (Spawn), where players cant get damaged, break or place blocks. =======
#======= Not tested!! Unfinished! =======
options:
	spawnworldname: world

#======= This command lets you set a round area with the given Radius as the Spawn =======
command /setspawnprotection <integer>:
	permission: set.spawn
	trigger:
		set {_loc} to location of player
		set {_radius} to arg-1
		loop all blocks in radius {_radius}:
			add location of block to {spawnblocks::*}

#======= This command lets you set a square as the Spawn. Use /setspawnloc1 for the first Edge and /setspawnloc2 for the opposite corner =======
command /setspawnloc1:
	permission: set.spawn
	trigger:
		set {spawnedge1x} to x-location of player
		set {spawnedge1z} to z-location of player

		send "<#18FF00>Edge 1 set! Use /setspawnloc2 to set the second corner!"

command /setspawnloc2:
	permission: set.spawn
	trigger:
		set {spawnedge2x} to x-location of player
		set {spawnedge2z} to z-location of player
		set {spawnworld} to world "{@spawnworldname}"
		send "<#18FF00>Edge 2 set! Spawnprotection set!"

on block break:
	if world of player = {spawnworld}:
		if x-location of event-block is between {spawnedge1x} and {spawnedge2x}:
			if z-location of event-block is between {spawnedge1z} and {spawnedge2z}:
				cancel event
				send "<#FF0000>You can't place blocks at spawn!"
		else if {spawnblocks::*} contains location of event-block:
			cancel event
			send "<#FF0000>You can't place blocks at spawn!"
			
on place:
	if world of player = {spawnworld}:
		if x-location of event-block is between {spawnedge1x} and {spawnedge2x}:
			if z-location of event-block is between {spawnedge1z} and {spawnedge2z}:
				cancel event
				send "<#FF0000>You can't place blocks at spawn!"
		else if {spawnblocks::*} contains location of event-block:
			cancel event
			send "<#FF0000>You can't place blocks at spawn!"

on damage:
	if world of victim = {spawnworld}:
		if x-location of victim is between {spawnedge1x} and {spawnedge2x}:
			if z-location of victim is between {spawnedge1z} and {spawnedge2z}:
		else if {spawnblocks::*} contains location of victim:
				cancel event
				send "<#FF0000>You can't attack players at spawn!" to attacker





