#======= Skript for the /tpa command =======
command /tpa <player>:
	trigger:
		if {tpasent.%player%} is true:
			send actionbar "<#FF0000>You have already sent a TPA-Request"
			stop
		set {_sender} to player
		set {_receiver} to arg-1
		set {tpaaccepted.%{_sender}%} to false
		set {tpalatest.%{_receiver}%} to {_sender}
		set {tpalatest.%{_sender}%} to {_receiver}
		set {tpasent.%{_sender}%.%{_receiver}%} to true
		send "<#18FF00>You received a TPA-Request from <#FFE300>%{_sender}%<#18FF00>!" to {_receiver}
		send "<#18FF00>TPA-Request sent to <#FFE300>%{_receiver}%<#18FF00>!"
		set {tpasent.%{_sender}%} to true
		wait 1 minute
		if {tpaaccepted.%{_sender}%} is false:
			send actionbar "<#FF0000>TPA-Request timed out" to {_sender}
			delete {tpaaccepted.%{_sender}%}
			delete {tpasent.%{_sender}%.%{_receiver}%}
			delete {tpasent.%{_sender}%}
			delete {tpalatest.%{_receiver}%}
			delete {tpalatest.%{_sender}%}
		else if {tpaaccepted.%{_sender}%} is true:
			delete {tpaaccepted.%{_sender}%}
			delete {tpasent.%{_sender}%.%{_receiver}%}
			delete {tpasent.%{_sender}%}
			delete {tpalatest.%{_receiver}%}
			delete {tpalatest.%{_sender}%}
			stop

#======= TPAHere Command =======
command /tpahere <player>:
	trigger:
		if {tpaheresent.%player%} is true:
			send actionbar "<#FF0000>You have already sent a TPAHere-Request"
			stop
		set {_sender} to player
		set {_receiver} to arg-1
		set {tpahereaccepted.%{_sender}%} to false
		set {tpaherelatest.%{_receiver}%} to {_sender}
		set {tpaherelatest.%{_sender}%} to {_receiver}
		set {tpaheresent.%{_sender}%.%{_receiver}%} to true
		send "<#18FF00>You received a TPAHere-Request from <#FFE300>%{_sender}%<#18FF00>!" to {_receiver}
		send "<#18FF00>TPAHere-Request sent to <#FFE300>%{_receiver}%<#18FF00>!"
		set {tpaheresent.%{_sender}%} to true
		wait 1 minute
		if {tpahereaccepted.%{_sender}%} is false:
			send actionbar "<#FF0000>TPAHere-Request timed out" to {_sender}
			delete {tpahereaccepted.%{_sender}%}
			delete {tpaheresent.%{_sender}%.%{_receiver}%}
			delete {tpaheresent.%{_sender}%}
			delete {tpaherelatest.%{_receiver}%}
			delete {tpaherelatest.%{_sender}%}
		else if {tpahereaccepted.%{_sender}%} is true:
			delete {tpahereaccepted.%{_sender}%}
			delete {tpaheresent.%{_sender}%.%{_receiver}%}
			delete {tpaheresent.%{_sender}%}
			delete {tpaherelatest.%{_receiver}%}
			delete {tpaherelatest.%{_sender}%}
			stop


command /tpaccept [<player>]:
	aliases: tpaaccept
	trigger:
		set {_receiver} to player
		if arg-1 is set:
			set {_sender} to arg-1
		else:
			if {tpasent.%{tpalatest.%{_receiver}%}%.%{_receiver}%} is true:
				set {_sender} to {tpalatest.%{_receiver}%}
			else if {tpaheresent.%{tpaherelatest.%{_receiver}%}%.%{_receiver}%} is true:
				set {_sender} to {tpaherelatest.%{_receiver}%}
		
		if {tpasent.%{_sender}%.%{_receiver}%} is true:
			set {tpaaccepted.%{_sender}%} to true
			delete {tpasent.%{_sender}%.%{_receiver}%}
			delete {tpasent.%{_sender}%}
			delete {tpalatest.%{_receiver}%}
			delete {tpalatest.%{_sender}%}
			
			send actionbar "<#18FF00>Accepted TPA-Request from <#FFE300>%{_sender}%<#18FF00>!" to {_receiver}
			
			set {_locx} to x-coordinate of player
			set {_locy} to y-coordinate of player
			set {_locz} to z-coordinate of player
			send actionbar "<#18FF00>You will be teleported to spawn in 5 seconds, don't move!"
			set {_number} to 5
			wait 1 second
			loop 5 times:
				if {_locx} = x-coordinate of player:
					if {_locy} = y-coordinate of player:
						if {_locz} = z-coordinate of player:
							send actionbar "<#FFE300>You will be teleported in <#18FF00>%{_number}%<#FFE300> seconds!"
							remove 1 from {_number}
							wait 1 second
						else:
							send "<#FF0000>You moved! Teleport cancelled!"
							stop
					else:
						send "<#FF0000>You moved! Teleport cancelled!"
						stop
				else:
					send "<#FF0000>You moved! Teleport cancelled!"
					stop
			teleport {_sender} to {_receiver}
			stop

		else if {tpaheresent.%{_sender}%.%{_receiver}%} is true:
			set {tpahereaccepted.%{_sender}%} to true
			delete {tpaheresent.%{_sender}%.%{_receiver}%}
			delete {tpaheresent.%{_sender}%}
			delete {tpaherelatest.%{_receiver}%}
			delete {tpaherelatest.%{_sender}%}
			
			send actionbar "<#18FF00>Accepted TPAHere-Request from <#FFE300>%{_sender}%<#18FF00>!" to {_receiver}
			
			set {_locx} to x-coordinate of player
			set {_locy} to y-coordinate of player
			set {_locz} to z-coordinate of player
			send actionbar "<#18FF00>You will be teleported to spawn in 5 seconds, don't move!"
			set {_number} to 5
			wait 1 second
			loop 5 times:
				if {_locx} = x-coordinate of player:
					if {_locy} = y-coordinate of player:
						if {_locz} = z-coordinate of player:
							send actionbar "<#FFE300>You will be teleported in <#18FF00>%{_number}%<#FFE300> seconds!"
							remove 1 from {_number}
							wait 1 second
						else:
							send "<#FF0000>You moved! Teleport cancelled!"
							stop
					else:
						send "<#FF0000>You moved! Teleport cancelled!"
						stop
				else:
					send "<#FF0000>You moved! Teleport cancelled!"
					stop
			teleport {_receiver} to {_sender}
			stop
			
		else:
			send "<#FF0000>You don't have any active teleport requests!" to {_receiver}



