#======= Skript for the /tpa command =======
#======= Unfinished! =======
#======= Untested! =======
command /tpa <player>:
	trigger:
		if {tpasent.%{_sender}%} is set to true:
			send actionbar "You have already sent a TPA-Request"
			stop
		set {_sender} to player
		set {_receiver} to arg-1
		set {tpaaccepted.%{_sender}%} to false
		set {tpasent::%{_sender}%::%{_receiver}%} to true
		send actionbar "You received a TPA-Request from %{_sender}%!" to {_receiver}
		send actionbar "TPA-Request sent to %{_receiver}%"
		set {tpasent.%{_sender}%} to true
		wait 1 minute
		delete {tpasent.%{_sender}%}
		if {tpaaccepted.%{_sender}%} is set to false:
			send actionbar "TPA-Request timed out"
		else if {tpaaccepted.%{_sender}%} is set to true:
			delete {tpaaccepted.%{_sender}%}
			stop

command /tpaccept <player>:
	aliases: tpaaccept
	trigger:
		set {_sender} to arg-1
		set {_receiver} to player
		if {tpasent::%{_sender}%::%{_receiver}%} is set to true:
			set {tpaaccepted.%{_sender}%} to true
			set {tpasent.%{_sender}%} to false
			set {tpasent::%{_sender}%::%{_receiver}%} to false
			